import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import NavBar from "@/components/navigation/navBar";
import SideBar from "@/components/navigation/sideBar";

const geistSans = localFont({
  src: "../fonts/Roboto-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/Roboto-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-200 lg:flex`}
      >
        <div className="hidden lg:block lg:w-1/5 lg:h-full">
          <SideBar />
        </div>
        <div className="w-full lg:w-4/5">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
