import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import "../globals.css";
import NavBar from "@/components/navigation/navBar";
import SideBar from "@/components/navigation/sideBar";
import { Roboto } from "next/font/google";
import { ClientProvider } from "@/context/client-context";

const mainFontFamily = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-main",
});

// const geistSans = localFont({
//   src: "../fonts/Montserrat-VariableFont_wght.ttf",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/Montserrat-VariableFont_wght.ttf",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mainFontFamily.variable} antialiased`}>
      <body className={`antialiased bg-slate-200 lg:flex`}>
        <ClientProvider>
          <div className="hidden lg:block lg:w-1/5 lg:h-full">
            <SideBar />
          </div>
          <div className="w-full lg:w-4/5">
            <NavBar />
            {children}
            <Toaster />
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
